// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7jd5wPFqaprDoONaLdGg6I8uZk9AKu2c',
    appId: '1:37056920650:web:978b1c68f627a55a347ab3',
    messagingSenderId: '37056920650',
    projectId: 'sigar-d063d',
    authDomain: 'sigar-d063d.firebaseapp.com',
    storageBucket: 'sigar-d063d.firebasestorage.app',
    measurementId: 'G-BLSEPJ7R7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2kSH01hjjmQ2mEfBuTsDHdhNyvB1UoIs',
    appId: '1:37056920650:android:0c725a4a63d20857347ab3',
    messagingSenderId: '37056920650',
    projectId: 'sigar-d063d',
    storageBucket: 'sigar-d063d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5pmjKiLcq3nKBPEEqMhJmflx6cOdJbss',
    appId: '1:37056920650:ios:46340c33ddb65296347ab3',
    messagingSenderId: '37056920650',
    projectId: 'sigar-d063d',
    storageBucket: 'sigar-d063d.firebasestorage.app',
    iosBundleId: 'io.sigar.sigar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5pmjKiLcq3nKBPEEqMhJmflx6cOdJbss',
    appId: '1:37056920650:ios:46340c33ddb65296347ab3',
    messagingSenderId: '37056920650',
    projectId: 'sigar-d063d',
    storageBucket: 'sigar-d063d.firebasestorage.app',
    iosBundleId: 'io.sigar.sigar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7jd5wPFqaprDoONaLdGg6I8uZk9AKu2c',
    appId: '1:37056920650:web:5c3c3551795df08f347ab3',
    messagingSenderId: '37056920650',
    projectId: 'sigar-d063d',
    authDomain: 'sigar-d063d.firebaseapp.com',
    storageBucket: 'sigar-d063d.firebasestorage.app',
    measurementId: 'G-0LC7MM0EXT',
  );
}
